<script lang="ts">
import { TrainObject } from "@/types";
import { Component, Inject, Prop, Vue, toNative } from "vue-facing-decorator";
import { GameConfig, GAME_CONFIG_KEY } from "@/gameConfig";
import type { Game } from "@/game";
import {
  freightVariantFor,
  locoSvg,
  locoViewBox,
  wagonSvg,
  wagonViewBox,
} from "@/utils/trainArt";

// Train is a pure renderer: it draws the locomotive + wagon art and the game loop
// (see game.ts) positions them each frame from the simulation. It owns no
// movement, animation, or pathfinding logic.
//
// The art is SVG generated by `utils/trainArt.ts` rather than bitmaps. Two things
// that used to be awkward fall out of that: a unit's livery is a real `fill`
// (the PNGs were recoloured by a stack of `grayscale/sepia/hue-rotate` filters,
// which is why the old palette classes are gone), and a freight wagon's body is
// chosen from its id instead of at random per render.
@Component
class Train extends Vue {
  @Inject({ from: GAME_CONFIG_KEY }) config!: GameConfig;
  @Inject({ from: "game" }) game!: Game;
  @Prop({ type: Object, default: () => ({}) }) trainObject!: TrainObject;

  get type(): "people" | "fraight" {
    return this.trainObject.type;
  }

  get trainColor(): string {
    return this.game.trainColors[this.trainObject.id] ?? "grey";
  }

  get locoBox(): string {
    return locoViewBox(this.type);
  }

  get wagonBox(): string {
    return wagonViewBox(this.type);
  }

  get locoArt(): string {
    return locoSvg(this.type, this.trainColor);
  }

  // Freight bodies vary per wagon; coaches are all the same. Derived from the
  // wagon id so a consist looks identical on every load (and in screenshots).
  wagonArt(wagonId: string): string {
    return wagonSvg(this.type, this.trainColor, freightVariantFor(wagonId));
  }
}

export default toNative(Train);
</script>

<template>
  <div class="train-composition">
    <div :id="trainObject.id" class="train train-locomotive">
      <svg class="train-art" :viewBox="locoBox" v-html="locoArt" />
      <span v-if="config.debug" class="train-debug">{{ trainObject.id }}</span>
    </div>
    <template v-if="trainObject.wagons">
      <div
        v-for="wagon in trainObject.wagons"
        :id="wagon.id"
        :key="wagon.id"
        class="train train-wagon"
        :class="`train-wagon--${type}`"
      >
        <svg class="train-art" :viewBox="wagonBox" v-html="wagonArt(wagon.id)" />
        <span v-if="config.debug" class="train-debug">{{ wagon.id }}</span>
      </div>
    </template>
  </div>
</template>

<style lang="scss" scoped>
// A composition is a pure wrapper — every unit inside it is absolutely positioned
// against the `.level` grid by the game loop, so the wrapper itself must generate
// NO box. Without this it is a plain static div and therefore a GRID ITEM, eating
// one 200px cell each: the whole board slid one tile to the right per train and
// wrapped its tail onto an extra row (2 trains on /play started the level at
// column 2). `display: contents` removes the box without changing the units'
// containing block, which stays `.level` — do not swap it for `position:
// absolute`, that would re-anchor every transform the game loop writes.
.train-composition {
  display: contents;
}

.train {
  position: absolute;
  z-index: 10;
  top: 0;
  left: 0;
  transform: translate(-50%, -50%);
  will-change: transform;

  // NOTE: these sprite widths are the on-screen unit lengths the simulation
  // uses to space coupled units. They MUST match UNIT_PX in
  // src/sim/trainDimensions.ts (the single source of truth the sim reads), and
  // the heights must match UNIT_H in src/utils/trainArt.ts (which sets the art's
  // viewBox) — keep the three in sync when changing a sprite size.
  &.train-locomotive {
    width: 100px;
    height: 26px;
    // Layer order at a crossing: road (z1) < rails (z2) < wagons (z3) <
    // locomotive (z4). Both train units sit above the track so the train is
    // never hidden behind the rails it runs on.
    z-index: 4;
  }
  &.train-wagon {
    z-index: 3; // above the rails (z2); see the locomotive note above
  }
  &.train-wagon--people {
    width: 100px;
    height: 30px;
  }
  &.train-wagon--fraight {
    width: 81px;
    height: 30px;
  }
}

// The art fills its unit box exactly (the viewBox is authored at the same CSS
// pixel size), and casts the same soft shadow the road cars do, so rolling stock
// and traffic sit on the world the same way.
.train-art {
  display: block;
  width: 100%;
  height: 100%;
  overflow: visible;
  filter: drop-shadow(0 2px 3px rgba(0, 0, 0, 0.4));
}

.train-debug {
  font-size: 14px;
  font-weight: bold;
  position: absolute;
  color: black;
  width: 100%;
  // Cancel the unit's own rotation so the id stays upright and readable whichever
  // way the train is running (`--unit-angle` is published by the game loop next to
  // the transform it belongs to). Westbound trains sit at ~180deg, which used to
  // render their ids mirrored and upside down.
  transform: translate(-50%, -50%) rotate(calc(-1 * var(--unit-angle, 0deg)));
  top: 50%;
  left: 50%;
}
</style>
