// Procedural rolling-stock art: the locomotives, wagons and depot shed, drawn as
// SVG instead of bitmaps.
//
// Why this exists: the train sprites were the last third-party bitmaps in the
// project (see ASSETS.md) while everything else on the board — rails, roads,
// markings, crossings, terrain, foliage — is generated by our own code. Drawing
// them here removes the last licensing question, lets a unit take its livery from
// a real `fill` instead of the stack of `filter: sepia() hue-rotate()` hacks the
// PNGs needed, and keeps the art crisp at any camera zoom (a 200px board tile can
// now be magnified well past a 900px sprite's resolution).
//
// Everything is a pure function returning SVG markup, in the style of
// `utils/foliage.ts`: flat fills with a lit/shade split rather than gradients, so
// the trains sit in the same visual language as the cars and the scenery.
//
// Geometry is in CSS pixels, matching the sprite boxes in `Train.vue`, and the
// widths come from `UNIT_PX` so the art can never drift from the lengths the
// simulation spaces couplings by.

import { UNIT_PX, TrainKind } from "@/sim/trainDimensions";

// Sprite heights in CSS px. Widths live in `sim/trainDimensions.ts` because the
// simulation reads them; heights are art-only, so they live here.
export const UNIT_H = {
  loco: 26,
  wagon: 30,
} as const;

export const locoViewBox = (kind: TrainKind) =>
  `0 0 ${UNIT_PX.loco[kind]} ${UNIT_H.loco}`;
export const wagonViewBox = (kind: TrainKind) =>
  `0 0 ${UNIT_PX.wagon[kind]} ${UNIT_H.wagon}`;

/** A unit's livery: the base colour plus the lit/shade tones derived from it. */
export interface Livery {
  body: string;
  light: string;
  dark: string;
}

// The five names `utils/globalHelpers.ts` `Colors` assigns, plus black, mapped to
// a livery that reads as painted metal rather than a raw CSS keyword (`red` and
// `blue` at full saturation look like UI, not like a train). An unknown value —
// a hex, say — falls through as its own body colour so callers are never wrong,
// only less shaded.
const LIVERIES: Record<string, Livery> = {
  green: { body: "#3f9d5a", light: "#5cc07b", dark: "#2a6c3e" },
  yellow: { body: "#e0ae35", light: "#f6cf63", dark: "#a67a1e" },
  red: { body: "#c4483d", light: "#e17064", dark: "#8d2f26" },
  blue: { body: "#3d74b4", light: "#5f98d8", dark: "#2a5182" },
  grey: { body: "#8a939b", light: "#aab3ba", dark: "#616a71" },
  black: { body: "#454b52", light: "#626a72", dark: "#2b2f34" },
};

export function livery(color: string): Livery {
  return LIVERIES[color] ?? { body: color, light: color, dark: color };
}

// Shared detail tones. Deliberately few: the eye should read the livery first and
// the details second.
const GLASS = "rgba(185, 222, 255, 0.92)"; // matches `.road-car-glass`
const STEEL = "#5b6167";
const STEEL_DARK = "#3a3f44";
const LAMP = "#ffe9a8";
const TIMBER = "#8a6236";
const TIMBER_DARK = "#6b4a2b";

const n = (v: number) => v.toFixed(1);

/**
 * The roof of a unit: the body plate, a lighter ridge running along the centre
 * and darker slivers down both long edges. Seen from above this is what gives a
 * flat shape its volume — the roof crowns in the middle and falls away to the
 * sides. Every unit starts with one of these.
 */
function roof(
  x: number,
  w: number,
  h: number,
  lv: Livery,
  radius = 4,
): string {
  const edge = h * 0.16; // how much of each side is in shadow
  // The lit ridge is a NARROW crown, not half the roof: widening it makes the
  // body read as three stripes rather than one rounded solid.
  const ridgeH = h * 0.3;
  const ridgeY = (h - ridgeH) / 2;
  return (
    `<rect x="${n(x)}" y="0" width="${n(w)}" height="${n(h)}" rx="${radius}" fill="${lv.dark}"/>` +
    `<rect x="${n(x)}" y="${n(edge)}" width="${n(w)}" height="${n(h - edge * 2)}" rx="${n(Math.max(1, radius - 1))}" fill="${lv.body}"/>` +
    `<rect x="${n(x + 1)}" y="${n(ridgeY)}" width="${n(w - 2)}" height="${n(ridgeH)}" rx="${n(Math.max(1, radius - 2))}" fill="${lv.light}"/>`
  );
}

/** A row of small dark windows down both flanks — what makes a coach a coach. */
function sideWindows(
  x: number,
  w: number,
  h: number,
  count: number,
): string {
  const winW = (w / count) * 0.74;
  const gap = w / count;
  const inset = h * 0.13;
  const winH = h * 0.16;
  let out = "";
  for (let i = 0; i < count; i++) {
    const wx = x + gap * i + (gap - winW) / 2;
    out +=
      `<rect x="${n(wx)}" y="${n(inset)}" width="${n(winW)}" height="${n(winH)}" rx="1" fill="${GLASS}"/>` +
      `<rect x="${n(wx)}" y="${n(h - inset - winH)}" width="${n(winW)}" height="${n(winH)}" rx="1" fill="${GLASS}"/>`;
  }
  return out;
}

/** The buffer beam / coupler stub drawn at a unit end (`side`: -1 rear, +1 front). */
function buffers(atX: number, h: number, side: -1 | 1): string {
  const w = 2.4;
  const x = side === 1 ? atX : atX - w;
  return (
    `<rect x="${n(x)}" y="${n(h * 0.26)}" width="${n(w)}" height="${n(h * 0.48)}" rx="1" fill="${STEEL_DARK}"/>`
  );
}

/**
 * A locomotive. Local +x is the direction of travel, so the nose is at the right
 * — the game loop rotates the whole sprite to the path tangent, where 0° is east.
 *
 * `people` is a sleek express loco (tapered nose, wide windscreen); `fraight` is
 * a stubby shunter with a boiler, chimney and a cab set back at the rear. Both
 * carry the livery on their main body so a train's colour — which is what the
 * player actually matches against a depot — reads at a glance.
 */
export function locoSvg(kind: TrainKind, color: string): string {
  const lv = livery(color);
  const w = UNIT_PX.loco[kind];
  const h = UNIT_H.loco;

  if (kind === "people") {
    const noseX = w - 16;
    return (
      buffers(1, h, -1) +
      roof(2, w - 6, h, lv) +
      // Tapered nose: the body's right end drawn back to a blunt point.
      `<path d="M${n(noseX)} ${n(h * 0.06)} L${n(w - 5)} ${n(h * 0.06)} Q${n(w - 1)} ${n(h / 2)} ${n(w - 5)} ${n(h * 0.94)} L${n(noseX)} ${n(h * 0.94)} Z" fill="${lv.body}"/>` +
      `<path d="M${n(noseX)} ${n(h * 0.26)} L${n(w - 7)} ${n(h * 0.26)} Q${n(w - 4)} ${n(h / 2)} ${n(w - 7)} ${n(h * 0.74)} L${n(noseX)} ${n(h * 0.74)} Z" fill="${lv.light}"/>` +
      // Windscreen, then roof vents receding toward the tail.
      `<path d="M${n(noseX - 9)} ${n(h * 0.2)} L${n(noseX - 1)} ${n(h * 0.2)} L${n(noseX - 1)} ${n(h * 0.8)} L${n(noseX - 9)} ${n(h * 0.8)} Z" fill="${GLASS}"/>` +
      `<rect x="${n(w * 0.2)}" y="${n(h * 0.34)}" width="${n(w * 0.3)}" height="${n(h * 0.32)}" rx="2" fill="${STEEL}"/>` +
      `<rect x="${n(w * 0.55)}" y="${n(h * 0.38)}" width="${n(w * 0.08)}" height="${n(h * 0.24)}" rx="1" fill="${STEEL_DARK}"/>` +
      // Headlamps at the nose.
      `<circle cx="${n(w - 4)}" cy="${n(h * 0.32)}" r="1.5" fill="${LAMP}"/>` +
      `<circle cx="${n(w - 4)}" cy="${n(h * 0.68)}" r="1.5" fill="${LAMP}"/>`
    );
  }

  // Freight: boiler forward, cab aft.
  const cabW = w * 0.34;
  const boilerX = cabW + 2;
  const boilerW = w - boilerX - 4;
  return (
    buffers(1, h, -1) +
    // Running plate the whole length, so boiler and cab sit on one chassis.
    `<rect x="2" y="${n(h * 0.16)}" width="${n(w - 5)}" height="${n(h * 0.68)}" rx="3" fill="${STEEL_DARK}"/>` +
    roof(2, cabW, h, lv) +
    `<rect x="${n(cabW * 0.28)}" y="${n(h * 0.24)}" width="${n(cabW * 0.44)}" height="${n(h * 0.52)}" rx="1.5" fill="${GLASS}"/>` +
    // Boiler: a livery cylinder with banding, blunt at the smokebox end.
    `<rect x="${n(boilerX)}" y="${n(h * 0.2)}" width="${n(boilerW)}" height="${n(h * 0.6)}" rx="${n(h * 0.3)}" fill="${lv.dark}"/>` +
    `<rect x="${n(boilerX)}" y="${n(h * 0.27)}" width="${n(boilerW)}" height="${n(h * 0.46)}" rx="${n(h * 0.23)}" fill="${lv.body}"/>` +
    `<rect x="${n(boilerX + 2)}" y="${n(h * 0.36)}" width="${n(boilerW - 6)}" height="${n(h * 0.16)}" rx="${n(h * 0.08)}" fill="${lv.light}"/>` +
    `<rect x="${n(boilerX + boilerW * 0.34)}" y="${n(h * 0.2)}" width="1.6" height="${n(h * 0.6)}" fill="${lv.dark}"/>` +
    `<rect x="${n(boilerX + boilerW * 0.62)}" y="${n(h * 0.2)}" width="1.6" height="${n(h * 0.6)}" fill="${lv.dark}"/>` +
    // Steam dome, then the smokebox: a dark band capping the boiler's front with
    // the chimney standing on it. Without the band the chimney circle sat alone
    // at the nose and read as a hole punched in the loco.
    `<circle cx="${n(boilerX + boilerW * 0.24)}" cy="${n(h / 2)}" r="${n(h * 0.16)}" fill="${STEEL}"/>` +
    `<rect x="${n(w - 20)}" y="${n(h * 0.18)}" width="16" height="${n(h * 0.64)}" rx="${n(h * 0.32)}" fill="${STEEL_DARK}"/>` +
    `<circle cx="${n(w - 13)}" cy="${n(h / 2)}" r="${n(h * 0.2)}" fill="#23262a"/>` +
    `<circle cx="${n(w - 13)}" cy="${n(h / 2)}" r="${n(h * 0.1)}" fill="#15171a"/>` +
    `<circle cx="${n(w - 5.5)}" cy="${n(h / 2)}" r="1.8" fill="${LAMP}"/>`
  );
}

/** How many distinct freight wagon bodies exist. */
export const FREIGHT_VARIANTS = 4;

/**
 * Which freight body a wagon gets: a hash of its id, so the same wagon always
 * draws the same way. The PNG renderer picked one at random *per render*, which
 * meant a freight train reshuffled its own consist on every reload and made
 * `npm run shot` screenshots incomparable. Deriving it from the id follows the
 * same rule as terrain scatter: art is a pure function of identity, never chance.
 */
export function freightVariantFor(id: string): number {
  let hash = 0;
  for (let i = 0; i < id.length; i++) hash = (hash * 31 + id.charCodeAt(i)) | 0;
  return Math.abs(hash) % FREIGHT_VARIANTS;
}

/**
 * A wagon. `people` is a coach with a full row of windows; `fraight` cycles four
 * bodies — box van, tanker, timber flat and open hopper — so a long consist has
 * visible variety, as the bitmap set did.
 */
export function wagonSvg(
  kind: TrainKind,
  color: string,
  variant = 0,
): string {
  const lv = livery(color);
  const w = UNIT_PX.wagon[kind];
  const h = UNIT_H.wagon;

  if (kind === "people") {
    return (
      buffers(1, h, -1) +
      buffers(w - 1, h, 1) +
      roof(2, w - 4, h, lv) +
      sideWindows(7, w - 14, h, 5) +
      // Door seams a third in from each end.
      `<rect x="${n(w * 0.33)}" y="${n(h * 0.12)}" width="1" height="${n(h * 0.76)}" fill="${lv.dark}"/>` +
      `<rect x="${n(w * 0.67)}" y="${n(h * 0.12)}" width="1" height="${n(h * 0.76)}" fill="${lv.dark}"/>`
    );
  }

  const chassis =
    buffers(1, h, -1) +
    buffers(w - 1, h, 1) +
    `<rect x="2" y="${n(h * 0.2)}" width="${n(w - 4)}" height="${n(h * 0.6)}" rx="2" fill="${STEEL_DARK}"/>`;

  switch (variant % FREIGHT_VARIANTS) {
    case 1: {
      // Tanker: a livery cylinder on a dark frame, with a filling hatch on top.
      const tx = 6;
      const tw = w - 12;
      return (
        chassis +
        `<rect x="${n(tx)}" y="${n(h * 0.12)}" width="${n(tw)}" height="${n(h * 0.76)}" rx="${n(h * 0.38)}" fill="${lv.dark}"/>` +
        `<rect x="${n(tx)}" y="${n(h * 0.2)}" width="${n(tw)}" height="${n(h * 0.6)}" rx="${n(h * 0.3)}" fill="${lv.body}"/>` +
        `<rect x="${n(tx + 3)}" y="${n(h * 0.31)}" width="${n(tw - 6)}" height="${n(h * 0.16)}" rx="${n(h * 0.08)}" fill="${lv.light}"/>` +
        `<circle cx="${n(w / 2)}" cy="${n(h / 2)}" r="${n(h * 0.17)}" fill="${STEEL}"/>` +
        `<rect x="${n(tx + tw * 0.22)}" y="${n(h * 0.12)}" width="1.4" height="${n(h * 0.76)}" fill="${lv.dark}"/>` +
        `<rect x="${n(tx + tw * 0.78)}" y="${n(h * 0.12)}" width="1.4" height="${n(h * 0.76)}" fill="${lv.dark}"/>`
      );
    }
    case 2: {
      // Timber flat: logs lying across a low deck, held by corner stakes.
      // Fat, pale logs: at 30px tall a thin dark log is indistinguishable from
      // the deck it lies on, and the whole wagon read as a black bar.
      const logs: string[] = [];
      const count = 4;
      const span = w - 18;
      const logW = span / count - 1.5;
      for (let i = 0; i < count; i++) {
        const lx = 9 + (span / count) * i + 0.75;
        logs.push(
          `<rect x="${n(lx)}" y="${n(h * 0.12)}" width="${n(logW)}" height="${n(h * 0.76)}" rx="${n(h * 0.12)}" fill="${TIMBER}"/>`,
          `<rect x="${n(lx)}" y="${n(h * 0.12)}" width="${n(logW)}" height="${n(h * 0.3)}" rx="${n(h * 0.12)}" fill="#b98d55"/>`,
          `<rect x="${n(lx)}" y="${n(h * 0.44)}" width="${n(logW)}" height="1" fill="${TIMBER_DARK}"/>`,
        );
      }
      return (
        chassis +
        `<rect x="4" y="${n(h * 0.24)}" width="${n(w - 8)}" height="${n(h * 0.52)}" rx="1" fill="${TIMBER_DARK}"/>` +
        logs.join("") +
        `<rect x="5" y="${n(h * 0.1)}" width="2" height="${n(h * 0.8)}" rx="1" fill="${lv.body}"/>` +
        `<rect x="${n(w - 7)}" y="${n(h * 0.1)}" width="2" height="${n(h * 0.8)}" rx="1" fill="${lv.body}"/>`
      );
    }
    case 3: {
      // Open hopper: livery walls, dark load, a few pale lumps of ballast.
      return (
        chassis +
        `<rect x="4" y="${n(h * 0.1)}" width="${n(w - 8)}" height="${n(h * 0.8)}" rx="2" fill="${lv.dark}"/>` +
        `<rect x="6" y="${n(h * 0.17)}" width="${n(w - 12)}" height="${n(h * 0.66)}" rx="1.5" fill="${lv.body}"/>` +
        // The load sits INSIDE a generous livery rim: filling the body with a
        // near-black load made the wagon a dark bar and cost it its colour
        // identity, which is the one thing a wagon has to communicate.
        `<rect x="13" y="${n(h * 0.3)}" width="${n(w - 26)}" height="${n(h * 0.4)}" rx="1.5" fill="#4a5054"/>` +
        `<circle cx="${n(w * 0.36)}" cy="${n(h * 0.45)}" r="2.4" fill="#6b7278"/>` +
        `<circle cx="${n(w * 0.5)}" cy="${n(h * 0.58)}" r="2.8" fill="#7b8288"/>` +
        `<circle cx="${n(w * 0.64)}" cy="${n(h * 0.43)}" r="2.2" fill="#6b7278"/>`
      );
    }
    default: {
      // Box van: a closed body with a sliding door down the middle.
      return (
        chassis +
        roof(4, w - 8, h, lv, 3) +
        `<rect x="${n(w / 2 - 7)}" y="${n(h * 0.14)}" width="14" height="${n(h * 0.72)}" rx="1" fill="${lv.dark}"/>` +
        `<rect x="${n(w / 2 - 6)}" y="${n(h * 0.19)}" width="12" height="${n(h * 0.62)}" rx="1" fill="${lv.body}"/>` +
        `<rect x="${n(w / 2 - 0.6)}" y="${n(h * 0.19)}" width="1.2" height="${n(h * 0.62)}" fill="${lv.dark}"/>` +
        `<rect x="${n(w * 0.16)}" y="${n(h * 0.3)}" width="${n(w * 0.1)}" height="${n(h * 0.4)}" rx="1" fill="${lv.dark}"/>` +
        `<rect x="${n(w * 0.74)}" y="${n(h * 0.3)}" width="${n(w * 0.1)}" height="${n(h * 0.4)}" rx="1" fill="${lv.dark}"/>`
      );
    }
  }
}

// --- depot -----------------------------------------------------------------

// The shed's own coordinate box. Rendered at `height: 70px` by `Tile.vue`, with
// the width following from this aspect — the same footprint the bitmap had, so
// the per-rotation placement CSS did not have to change.
export const DEPOT_W = 156;
export const DEPOT_H = 70;
export const depotViewBox = `0 0 ${DEPOT_W} ${DEPOT_H}`;

/**
 * The engine shed a train parks in, seen from above: a pitched roof with a ridge
 * along its length, and the portal at the RIGHT (+x) end where the track enters —
 * the rotation classes in `Tile.vue` turn that toward the tile centre.
 */
export function depotSvg(): string {
  const w = DEPOT_W;
  const h = DEPOT_H;
  // Slate and rendered concrete. An earlier pass painted the shed in browns and
  // it read as a stack of planks lying in the grass rather than as a building —
  // the grey industrial palette is what makes it legible as architecture at tile
  // scale, and it sits apart from the timber wagons and the trees.
  const ridge = "#5d656c";
  const slate = "#8e979f";
  const slateLit = "#aab3bb";
  const wall = "#c3c0b8";
  const wallShade = "#9d9a93";
  const doorX = w - 26;
  return (
    // Ground shadow, so the shed sits on the world instead of floating over it.
    `<rect x="3" y="${n(h * 0.14)}" width="${n(w - 5)}" height="${n(h * 0.74)}" rx="6" fill="rgba(0,0,0,0.22)"/>` +
    // Walls, visible as a rim below the roof overhang.
    `<rect x="4" y="${n(h * 0.12)}" width="${n(w - 8)}" height="${n(h * 0.76)}" rx="5" fill="${wallShade}"/>` +
    `<rect x="6" y="${n(h * 0.15)}" width="${n(w - 12)}" height="${n(h * 0.7)}" rx="4" fill="${wall}"/>` +
    // Pitched roof: the far slope in shade, the near slope lit, meeting at a
    // ridge that runs the length of the shed. Hipped at the closed (left) end.
    `<path d="M${n(doorX)} ${n(h * 0.2)} L${n(doorX)} ${n(h * 0.5)} L18 ${n(h * 0.5)} Q10 ${n(h * 0.35)} 18 ${n(h * 0.2)} Z" fill="${slateLit}"/>` +
    `<path d="M${n(doorX)} ${n(h * 0.5)} L${n(doorX)} ${n(h * 0.8)} L18 ${n(h * 0.8)} Q10 ${n(h * 0.65)} 18 ${n(h * 0.5)} Z" fill="${slate}"/>` +
    `<rect x="12" y="${n(h * 0.49)}" width="${n(doorX - 12)}" height="1.6" fill="${ridge}"/>` +
    // Two roof lights either side of the ridge.
    `<g fill="${ridge}" opacity="0.5">` +
    `<rect x="${n(w * 0.28)}" y="${n(h * 0.3)}" width="${n(w * 0.16)}" height="${n(h * 0.13)}" rx="1"/>` +
    `<rect x="${n(w * 0.56)}" y="${n(h * 0.3)}" width="${n(w * 0.16)}" height="${n(h * 0.13)}" rx="1"/>` +
    `<rect x="${n(w * 0.28)}" y="${n(h * 0.57)}" width="${n(w * 0.16)}" height="${n(h * 0.13)}" rx="1"/>` +
    `<rect x="${n(w * 0.56)}" y="${n(h * 0.57)}" width="${n(w * 0.16)}" height="${n(h * 0.13)}" rx="1"/>` +
    `</g>` +
    // The portal the track runs into, set in a gable end with a lintel and a
    // lamp. This is the one detail that tells the player which way the shed
    // faces, so it is the strongest contrast on the building.
    `<rect x="${n(doorX)}" y="${n(h * 0.14)}" width="${n(w - doorX - 4)}" height="${n(h * 0.72)}" rx="3" fill="${wallShade}"/>` +
    `<rect x="${n(doorX + 2)}" y="${n(h * 0.24)}" width="${n(w - doorX - 8)}" height="${n(h * 0.52)}" rx="2" fill="#2d3135"/>` +
    `<rect x="${n(doorX + 2)}" y="${n(h * 0.24)}" width="${n(w - doorX - 8)}" height="${n(h * 0.08)}" rx="1" fill="${ridge}"/>` +
    `<circle cx="${n(doorX - 4)}" cy="${n(h * 0.5)}" r="2.6" fill="${LAMP}"/>`
  );
}
